name: 从ROM提取boot并修补

on:
  workflow_dispatch:
    inputs:
      rom_url:
        description: '卡刷包ROM 下载直链'
        required: true
        default: ''
      note:
        description: '备注:'
        required: false
        default: ''
jobs:
  magisk_upack:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get -y install aria2 unzip img2simg
          BUILD_TIME=$(TZ=Asia/Shanghai date +"%m%d%H%M")
          echo "BUILD_TIME=$BUILD_TIME" >> $GITHUB_ENV
      - name: 提取镜像
        run: |
          cd ${{ github.workspace }}
          aria2c -s 5 -x 5 -d . -o firmware.zip "${{ github.event.inputs.rom_url }}"
          unzip firmware.zip payload.bin payload_properties.txt
          chmod +x ./payload-dumper-go
          ./payload-dumper-go -p boot payload.bin
          
      - name: 修补boot
        run: |
          cd ~
          git clone https://github.com/minglingshi/Magisk_patche.git Magisk
          cd Magisk
          mv ${{ github.workspace }}/out/* ./
          mkdir done
          cp boot.img done/
          ./boot.sh
          img2simg done/boot.img done/boot_sparse.img
          img2simg Magisk_boot*.img Magisk_boot_sparse.img
 
      - name: 提交信息
        run: |
          cd ${{ github.workspace }}
          touch info.md
          echo "提交日期：$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')" >> info.md
          echo "下载直链：${{ github.event.inputs.rom_url }}" >> info.md
          echo 'note: ${{ github.event.inputs.note }}' >> info.md
          echo '| key      | value |' >> info.md
          echo '| ----| --- |' >> info.md
          cat payload_properties.txt | awk -F= '{print $1,"|",$2 }' >> info.md

      - name: 上传镜像
        uses: ncipollo/release-action@v1.12.0
        with:
            artifacts: "~/Magisk/done/*"
            bodyfile: "${{ github.workspace }}/info.md"
            tag: "Magisk_${{ env.BUILD_TIME }}_${{ github.run_id }}"
            token: ${{ secrets.GITHUB_TOKEN }}
